# Generated by Django 5.2.12 on 2026-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('rh', 'Recruteur (RH)'), ('candidate', 'Candidat')], max_length=20),
        ),
    ]
