# Generated by Django 5.2.11 on 2026-02-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OffreQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('required', models.BooleanField(default=False)),
                ('input_type', models.CharField(choices=[('text', 'Texte'), ('textarea', 'Paragraphe'), ('file', 'Fichier')], default='text', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobs.offre')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
